name: Build & Publish Godot
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of Godot to build'
        required: true
      release:
        description: 'Add binary to releases'
        type: boolean
        default: true
      push_to_docker_hub:
        description: 'Push resulting container to Docker Hub'
        type: boolean
        default: true
      latest_release:
        description: 'Mark current build as latest'
        type: boolean
        default: true
env:
  CACHE_GODOT: cache_godot

jobs:
  build:
    runs-on: ubuntu-default
    steps:
      - name: Cache Godot
        id: cache-godot
        uses: actions/cache@v2
        with:
          path: godot/bin/godot_server.x11.opt.tools.64.llvm
          key: ${{ env.CACHE_GODOT }}
      - name: Build Godot on Alpine chroot
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/alpinelinux/alpine-chroot-install.git
          git clone https://github.com/godotengine/godot.git -b ${{ github.event.inputs.version }}-stable --depth 1
          sudo ./alpine-chroot-install/alpine-chroot-install
          /alpine/enter-chroot apk add scons pkgconf clang libx11-dev libxcursor-dev libxinerama-dev libxi-dev libxrandr-dev libexecinfo-dev
          /alpine/enter-chroot scons -C godot -j2 platform=server tools=yes target=release_debug use_llvm=yes LINKFLAGS=-lexecinfo
  release:
    if: github.event.inputs.release
    needs: build
    runs-on: ubuntu-default
    steps:
      - name: Cache Godot
        id: cache-godot
        uses: actions/cache@v2
        with:
          path: godot
          key: ${{ env.CACHE_GODOT }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Godot v${{ github.event.inputs.version }} headless for Alpine Linux
          files: godot
  docker:
    if: github.event.inputs.push_to_docker_hub
    needs: build
    runs-on: ubuntu-default
    steps:
      - uses: actions/checkout@v2
      - name: Cache Godot
        id: cache-godot
        uses: actions/cache@v2
        with:
          path: godot
          key: ${{ env.CACHE_GODOT }}
      - name: Login
        run: docker login -u wjykk -p ${{ secrets.dockerhub_password }}
      - name: Build container
        run: docker build -t xaltaq/godot-alpine:${{ github.event.inputs.version }} -t xaltaq/godot-alpine:latest .
      - name: Push versioned image to Docker Hub
        run: docker push xaltaq/godot-alpine:${{ github.event.inputs.version }}
      - name: Push latest image to Docker Hub
        if: github.event.inputs.latest_release
        run: docker push xaltaq/godot-alpine:latest
